In [24]:
from sklearn import datasets
from sklearn import tree, svm , naive_bayes
from sklearn.model_selection import train_test_split
from sklearn.utils import Bunch
import pandas as pd
import numpy as np


In [25]:
def _get_rbbdata(data):
    """
    获取双色球特征值
    :return:
    """
    # row = data.shape[0]
    col = data.shape[1]
    data_r = data.iloc[:, :col-1]
    data_np = np.array(data_r)
    return data_np


def _get_rbbtarget(data):
    """
    获取双色球目标值
    :return:
    """
    # row = data.shape[0]
    col = data.shape[1]
    data_b = data.iloc[:, col-1:col]
    data_np = np.array(data_b)
    return data_np


def _get_rbbdescr(data):
    """
    获取数据集描述
    :return:
    """
    text = "本数据集为final数据，样本数量：{}；" \
           "特征数量：{}；目标值数量：{}；无缺失数据" \
           "".format(data.index.size, data.columns.size - 1, 1)
    return text


def _get_feature_names(data):
    """
    获取特征名字
    :return:
    """
    col = data.shape[1]
    fnames = data.columns[:col-1].tolist()
    return fnames


def _get_target_names(data):
    """
    获取目标值名称
    :return:
    """
    col = data.shape[1]
    tnames = data.columns[col-1:].tolist()
    return tnames

def load_sklearn_dataset():
    data_csv = pd.read_csv("test_final.csv")
    rbb = Bunch()
    rbb.data = _get_rbbdata(data_csv)
    rbb.target = _get_rbbtarget(data_csv)
    rbb.DESCR = _get_rbbdescr(data_csv)
    rbb.feature_names = _get_feature_names(data_csv)
    rbb.target_names = _get_target_names(data_csv)
    return rbb

In [26]:
# wine = datasets.load_wine()
# print(wine)
rbb = load_sklearn_dataset()
X = rbb.data
Y = rbb.target
clf = tree.DecisionTreeClassifier() #决策树
clf = clf.fit(X, Y)
clf.predict([[0,0,0,0]])


array([1], dtype=int64)

In [27]:
clf2 = naive_bayes.GaussianNB()
clf2 = clf2.fit(X, Y.ravel())
clf2.predict([[0,0,0,0]])


array([1], dtype=int64)

In [28]:
clf3 = svm.SVC()
clf3 = clf3.fit(X, Y.ravel())
clf3.predict([[0,0,0,0]])

array([0], dtype=int64)